sensors:
  Sauna:
    addr: 90:fd:9f:00:00:00
    topic: tb/sauna
    type: tbs2
  Matbod:
    addr: 14:b4:57:00:00:00
    topic: tb/matbod
    type: tbbg22

mqtt:
  broker: '192.168.86.100'
  user: mosquitto
  password: passwd
  #cert: filename.pem

aes-key: 00000000000000000000000000000000

